import java.util.Vector
import java.lang.reflect.Field._
import java.lang.System.out
import java.lang.Math.PI
import java.lang.Math.cos
import java.lang.Math._
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.util.Vector
import java.lang.reflect.Field._
import java.lang.System.out
import java.lang.Math.PI
import java.lang.Math.cos
import java.lang.Math._
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.util.Vector
import java.lang.reflect.Field._
import java.lang.System.out
import java.lang.Math.PI
import java.lang.Math.cos
import java.lang.Math._
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.util.Vector
import java.lang.reflect.Field._
import java.lang.System.out
import java.lang.Math.PI
import java.lang.Math.cos
import java.lang.Math._
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.util.Vector
import java.lang.reflect.Field._
import java.lang.System.out
import java.lang.Math.PI
import java.lang.Math.cos
import java.lang.Math._
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.util.Vector
import java.lang.reflect.Field._
import java.lang.System.out
import java.lang.Math.PI
import java.lang.Math.cos
import java.lang.Math._
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.rmi._
import java.io._
import java.lang.Integer._
import java.lang.Long._
import java.lang.Math._
import java.lang.System.out
import java.util._
import java.util.Collections._
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
